### ISSUE TITLE
Does not work with iceborne

### ISSUE THREAD

**Issue by lan23333** [AsteriskAmpersand/MHW-Save-Editor#48]

**Comment by Trucasy0** [comment]
Please do an update for Iceborne, cause it wont work without.

**Comment by Rias213** [comment]
Can you give some kind of development status? When to expect a release?

**Comment by AsteriskAmpersand** [comment]
It does not work for iceborne. This project is deprecated, a python port is on the works. No ETA.

**Comment by mfish0005** [comment]
@AsteriskAmpersand Hey nice work.  I grok C# but don't know much about decrypting ciphers.  I'm trying to edit my save manually but can't figure out how to decrypt the damn thing. 

Here's what I've tried: 

1. Put a breakpoint on your `Decrypt()` method in `SaveFile.cs` 
2. Run the solution.  Open my save file using the tool.
3. When it hits the breakpoint check the `data` array to see the decrypted contents.

The problem is it looks to be decrypting it into another cipher?  Am I going about this the wrong way?
